version: '3.4'

volumes:
  lyzo_postgres: {}

services:
  lyzo:
    image: ${DOCKER_REGISTRY-}lyzo
    build:
      context: .
      dockerfile: Lyzo/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresConnectionString=Server=lyzo.postgres;Port=5432;User Id=lyzo;Password=lyzo;Database=lyzo;
      - Lyzo_RabbitMq=lyzo.rabbitmq
    depends_on:
      - lyzo.postgres
      - lyzo.rabbitmq

  lyzo.postgres:
    container_name: lyzo_postgres
    image: postgres
    labels:
      - lyzocompose
    ports:
      - "5432:5432"
      - "8080:8080"
    environment:
      - POSTGRES_USER=lyzo
      - POSTGRES_PASSWORD=lyzo
    volumes:
      - lyzo_postgres:/var/lib/postgresql/data
      - ./Module/Lyzo.Module.Rooms/Repository/Scripts/Rooms.sql:/docker-entrypoint-initdb.d/Rooms.sql

  lyzo.rabbitmq:
    image: docker.io/library/rabbitmq:3.8.6-management
    labels:
      - lyzocompose
    ports:
      - "15672:15672"